"""
Project Aegis - PDF Report Generator

Generates professional PDF reports for DDI analysis results using ReportLab.
"""

import io
import logging
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Color helpers
# ---------------------------------------------------------------------------

def _risk_color(score: float) -> colors.Color:
    """Return an RGB color based on risk score thresholds."""
    if score < 0.3:
        return colors.HexColor('#22c55e')   # green
    elif score < 0.6:
        return colors.HexColor('#eab308')   # yellow
    elif score < 0.8:
        return colors.HexColor('#f97316')   # orange
    else:
        return colors.HexColor('#ef4444')   # red


def _risk_label(score: float) -> str:
    if score < 0.3:
        return 'LOW'
    elif score < 0.6:
        return 'MODERATE'
    elif score < 0.8:
        return 'HIGH'
    else:
        return 'CRITICAL'


# ---------------------------------------------------------------------------
# Shared styles
# ---------------------------------------------------------------------------

def _build_styles():
    ss = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'AegisTitle',
        parent=ss['Title'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=4,
        alignment=TA_CENTER,
    )

    subtitle_style = ParagraphStyle(
        'AegisSubtitle',
        parent=ss['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748b'),
        alignment=TA_CENTER,
        spaceAfter=16,
    )

    section_style = ParagraphStyle(
        'AegisSection',
        parent=ss['Heading2'],
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=14,
        spaceAfter=6,
        borderPadding=(0, 0, 2, 0),
    )

    body_style = ParagraphStyle(
        'AegisBody',
        parent=ss['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6,
    )

    label_style = ParagraphStyle(
        'AegisLabel',
        parent=ss['Normal'],
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#64748b'),
    )

    disclaimer_style = ParagraphStyle(
        'AegisDisclaimer',
        parent=ss['Normal'],
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#94a3b8'),
        spaceBefore=24,
        alignment=TA_CENTER,
    )

    return {
        'title': title_style,
        'subtitle': subtitle_style,
        'section': section_style,
        'body': body_style,
        'label': label_style,
        'disclaimer': disclaimer_style,
    }


DISCLAIMER_TEXT = (
    "DISCLAIMER: This report is generated by an AI system and should not replace "
    "clinical judgment. Always consult qualified healthcare professionals before "
    "making clinical decisions based on these results."
)


# ---------------------------------------------------------------------------
# Shared elements
# ---------------------------------------------------------------------------

def _header_elements(styles, subtitle_text: str = ''):
    elements = []
    elements.append(Paragraph('Project Aegis', styles['title']))
    elements.append(Paragraph('Drug Interaction Report', styles['subtitle']))
    if subtitle_text:
        elements.append(Paragraph(subtitle_text, styles['subtitle']))
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    elements.append(Paragraph(f'Generated: {timestamp}', styles['label']))
    elements.append(Spacer(1, 6))
    elements.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#cbd5e1')))
    elements.append(Spacer(1, 12))
    return elements


def _disclaimer_elements(styles):
    elements = []
    elements.append(HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#e2e8f0')))
    elements.append(Paragraph(DISCLAIMER_TEXT, styles['disclaimer']))
    return elements


def _kv_table(pairs, styles):
    """Build a two-column key-value table from a list of (label, value) tuples."""
    data = []
    for label, value in pairs:
        data.append([
            Paragraph(f'<b>{label}</b>', styles['label']),
            Paragraph(str(value), styles['body']),
        ])
    if not data:
        return Spacer(1, 0)

    t = Table(data, colWidths=[2.0 * inch, 4.5 * inch])
    t.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (0, -1), 0),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, colors.HexColor('#f1f5f9')),
    ]))
    return t


# ---------------------------------------------------------------------------
# Pair report
# ---------------------------------------------------------------------------

def generate_pair_report(prediction_data: dict) -> bytes:
    """
    Generate a PDF report for a pairwise DDI prediction.

    Expected keys in *prediction_data*:
        drug_a, drug_b, risk_score, severity, confidence,
        mechanism_hypothesis, provenance (dict), class_warnings (list),
        risk_level, affected_systems, etc.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )

    styles = _build_styles()
    elements = []

    drug_a = prediction_data.get('drug_a', 'Unknown')
    drug_b = prediction_data.get('drug_b', 'Unknown')
    risk_score = float(prediction_data.get('risk_score', 0))
    severity = prediction_data.get('severity', 'unknown')
    confidence = prediction_data.get('confidence', None)
    mechanism = prediction_data.get('mechanism_hypothesis', '')
    provenance = prediction_data.get('provenance', {}) or {}
    class_warnings = prediction_data.get('class_warnings', []) or []
    risk_level = prediction_data.get('risk_level', _risk_label(risk_score))

    # Header
    elements.extend(_header_elements(styles, f'{drug_a}  +  {drug_b}'))

    # Drug pair
    elements.append(Paragraph('Drug Pair', styles['section']))
    elements.append(_kv_table([
        ('Drug A', drug_a),
        ('Drug B', drug_b),
    ], styles))
    elements.append(Spacer(1, 8))

    # Risk assessment
    elements.append(Paragraph('Risk Assessment', styles['section']))
    rc = _risk_color(risk_score)
    risk_display = (
        f'<font color="#{rc.hexval()[2:]}">{risk_score:.2f}</font>'
        f'  ({_risk_label(risk_score)})'
    )
    kv_pairs = [
        ('Risk Score', risk_display),
        ('Risk Level', str(risk_level).upper()),
        ('Severity', str(severity).replace('_', ' ').title()),
    ]
    if confidence is not None:
        kv_pairs.append(('Confidence', f'{float(confidence):.2f}'))
    elements.append(_kv_table(kv_pairs, styles))
    elements.append(Spacer(1, 8))

    # Mechanism
    if mechanism:
        elements.append(Paragraph('Mechanism Hypothesis', styles['section']))
        elements.append(Paragraph(mechanism, styles['body']))
        elements.append(Spacer(1, 8))

    # Provenance
    if provenance:
        elements.append(Paragraph('Model Provenance', styles['section']))
        prov_pairs = []
        if provenance.get('model_used'):
            prov_pairs.append(('Model Used', provenance['model_used']))
        if provenance.get('prediction_path'):
            prov_pairs.append(('Prediction Path', provenance['prediction_path']))
        if provenance.get('calibration_method'):
            prov_pairs.append(('Calibration', provenance['calibration_method']))
        if provenance.get('model_version'):
            prov_pairs.append(('Model Version', provenance['model_version']))
        if provenance.get('fallback_reason'):
            prov_pairs.append(('Fallback Reason', provenance['fallback_reason']))
        if prov_pairs:
            elements.append(_kv_table(prov_pairs, styles))
            elements.append(Spacer(1, 8))

    # Class warnings
    if class_warnings:
        elements.append(Paragraph('Drug Class Warnings', styles['section']))
        for w in class_warnings:
            w_type = 'Duplicate Therapy' if w.get('type') == 'duplicate_therapy' else 'Class Interaction'
            msg = w.get('message', '')
            sev = w.get('severity', 'medium')
            sev_color = '#ef4444' if sev == 'high' else '#f97316'
            elements.append(Paragraph(
                f'<font color="{sev_color}"><b>[{w_type.upper()}]</b></font> {msg}',
                styles['body'],
            ))
        elements.append(Spacer(1, 8))

    # Disclaimer
    elements.extend(_disclaimer_elements(styles))

    doc.build(elements)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Polypharmacy report
# ---------------------------------------------------------------------------

def generate_poly_report(polypharmacy_data: dict) -> bytes:
    """
    Generate a PDF report for polypharmacy (N-way) analysis.

    Expected keys in *polypharmacy_data*:
        drugs (list of names), interactions (list of edge dicts),
        overall_risk_level, hub_drug, hub_interaction_count,
        body_map (dict), risk_score / regimen_risk_score, etc.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )

    styles = _build_styles()
    elements = []

    drugs = polypharmacy_data.get('drugs', [])
    interactions = polypharmacy_data.get('interactions', [])
    overall_risk = polypharmacy_data.get('overall_risk_level', 'unknown')
    hub_drug = polypharmacy_data.get('hub_drug', '')
    hub_count = polypharmacy_data.get('hub_interaction_count', 0)
    body_map = polypharmacy_data.get('body_map', {}) or {}
    risk_score = float(
        polypharmacy_data.get('risk_score')
        or polypharmacy_data.get('regimen_risk_score')
        or 0
    )

    drug_list_str = ', '.join(str(d) for d in drugs) if drugs else 'N/A'

    # Header
    elements.extend(_header_elements(styles, 'Polypharmacy Analysis'))

    # Drug list
    elements.append(Paragraph('Drugs Analyzed', styles['section']))
    elements.append(Paragraph(drug_list_str, styles['body']))
    elements.append(Spacer(1, 8))

    # Overall risk
    elements.append(Paragraph('Overall Risk', styles['section']))
    rc = _risk_color(risk_score)
    risk_display = (
        f'<font color="#{rc.hexval()[2:]}">{risk_score:.2f}</font>'
        f'  ({_risk_label(risk_score)})'
    )
    kv_pairs = [
        ('Risk Score', risk_display),
        ('Overall Risk Level', str(overall_risk).upper()),
        ('Total Interactions', str(len(interactions))),
    ]
    elements.append(_kv_table(kv_pairs, styles))
    elements.append(Spacer(1, 8))

    # Hub drug
    if hub_drug:
        elements.append(Paragraph('Hub Drug', styles['section']))
        elements.append(_kv_table([
            ('Hub Drug', hub_drug),
            ('Interaction Count', str(hub_count)),
        ], styles))
        elements.append(Spacer(1, 8))

    # Interaction pairs table
    if interactions:
        elements.append(Paragraph('Interaction Pairs', styles['section']))
        header = ['Drug A', 'Drug B', 'Risk Score', 'Severity']
        table_data = [header]
        for edge in interactions:
            source = edge.get('source', edge.get('drug_a', ''))
            target = edge.get('target', edge.get('drug_b', ''))
            e_risk = float(edge.get('risk_score', 0))
            e_sev = str(edge.get('severity', 'unknown')).replace('_', ' ').title()
            table_data.append([source, target, f'{e_risk:.2f}', e_sev])

        col_widths = [1.7 * inch, 1.7 * inch, 1.3 * inch, 1.8 * inch]
        t = Table(table_data, colWidths=col_widths)
        t.setStyle(TableStyle([
            # Header row
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ALIGN', (2, 0), (2, -1), 'CENTER'),
            # Body rows
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 8))

    # Body map / affected systems
    if body_map:
        elements.append(Paragraph('Affected Body Systems', styles['section']))
        bm_pairs = []
        for system, severity_val in sorted(body_map.items()):
            if isinstance(severity_val, (int, float)):
                display = f'{severity_val:.2f}'
            else:
                display = str(severity_val)
            bm_pairs.append((system.replace('_', ' ').title(), display))
        elements.append(_kv_table(bm_pairs, styles))
        elements.append(Spacer(1, 8))

    # Disclaimer
    elements.extend(_disclaimer_elements(styles))

    doc.build(elements)
    return buf.getvalue()
