# Generated by Django 5.2.9 on 2026-01-04 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gene_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organism', models.CharField(default='Homo sapiens', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umls_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('organ_system', models.CharField(choices=[('brain', 'Brain/Nervous System'), ('heart', 'Cardiovascular'), ('liver', 'Hepatic'), ('kidney', 'Renal'), ('lungs', 'Respiratory'), ('gi', 'Gastrointestinal'), ('blood', 'Hematologic'), ('skin', 'Dermatologic'), ('musculoskeletal', 'Musculoskeletal'), ('endocrine', 'Endocrine'), ('other', 'Other')], default='other', max_length=50)),
                ('severity_weight', models.FloatField(default=0.5, help_text='0.0 (minor) to 1.0 (fatal)')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbank_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('smiles', models.TextField(blank=True, help_text='SMILES molecular notation', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('molecular_formula', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_class', models.CharField(blank=True, max_length=255, null=True)),
                ('atc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='ddi_api_dru_name_e04945_idx'), models.Index(fields=['drugbank_id'], name='ddi_api_dru_drugban_8886a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DrugTargetInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('inhibitor', 'Inhibitor'), ('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('substrate', 'Substrate'), ('binder', 'Binder'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('source', models.CharField(default='DrugBank', max_length=100)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi_api.drug')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi_api.drugtarget')),
            ],
            options={
                'unique_together': {('drug', 'target')},
            },
        ),
        migrations.AddField(
            model_name='drugtarget',
            name='drugs',
            field=models.ManyToManyField(related_name='targets', through='ddi_api.DrugTargetInteraction', to='ddi_api.drug'),
        ),
        migrations.CreateModel(
            name='DrugDrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], default='moderate', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('mechanism', models.TextField(blank=True, help_text='Mechanism of interaction', null=True)),
                ('affected_systems', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='DDIExtraction2013', max_length=100)),
                ('pubmed_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='ddi_api.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='ddi_api.drug')),
            ],
            options={
                'indexes': [models.Index(fields=['drug_a', 'drug_b'], name='ddi_api_dru_drug_a__02adf5_idx'), models.Index(fields=['severity'], name='ddi_api_dru_severit_2ee924_idx')],
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_list', models.JSONField(default=list)),
                ('risk_score', models.FloatField()),
                ('calibrated_score', models.FloatField(blank=True, null=True)),
                ('severity_prediction', models.CharField(blank=True, max_length=20)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('inference_time_ms', models.FloatField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ddi_api_pre_created_5f2acb_idx')],
            },
        ),
    ]
