# Generated by Django 5.2.9 on 2026-03-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='brand_names',
            field=models.JSONField(blank=True, default=list, help_text='List of brand names'),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='e.g., tablet, capsule, injection', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='ndc_code',
            field=models.CharField(blank=True, db_index=True, help_text='National Drug Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pill_color',
            field=models.CharField(blank=True, help_text='e.g., white, pink, blue', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pill_image_url',
            field=models.URLField(blank=True, help_text='URL to pill image', null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pill_imprint',
            field=models.CharField(blank=True, help_text='Text/numbers on pill', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pill_shape',
            field=models.CharField(blank=True, help_text='e.g., round, oval, capsule', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='rxcui',
            field=models.CharField(blank=True, help_text='RxNorm Concept Unique Identifier', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 10mg/ml', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='therapeutic_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
