# Generated by Django 5.2.9 on 2026-04-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi_api', '0003_predictionlog_raw_score_and_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='global', max_length=50, unique=True)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
